#!/bin/bash
set -ex

# Compile, Add+commit ALL changes in the working tree+output, then push it all.
# !!! STASH UNPUBLISHABLE CHANGES BEFOREHAND !!!

nanoc

# Unset this now; otherwise, ignored files cause the script to fail
set +e
git add *
set -e

git commit -m "$1"
git push

cd output
git add *
git commit -m "$1"
git push

cd ..
