---
title: Doctrine - Spokane Bible Church
description: Our statement of doctrine as a church.
---

= #Doctrine#


- God created man in His own image to rule over the earth.

-  ^────^
- *Man fell into sin, was separated from God, and turned over the rule of earth to Satan.*

-  ^────^
- Man became so wicked that God judged by way of a global flood and subsequently divided the language of Babel.

-  ^────^
- *God’s strategy to restore man’s rightful rule was to establish the nation Israel through whom He would provide the Scriptures and the Messiah.*

-  ^────^
- Messianic prophecies were fulfilled by Jesus who was born without sin, tempted in all things as we, yet without sin, demonstrated His power, and offered the kingdom to Israel.

-  ^────^
- *Jesus and the kingdom offer were rejected by Israel, resulting in His crucifixion for the sins of the whole world.*

-  ^────^
- God raised Jesus from the dead on the third day, providing salvation for all.

-  ^────^
- *Salvation is available to anyone by grace alone through faith alone in Him.*

-  ^────^
- Good works are not necessary for salvation but relate to reward and rule in the coming kingdom.

-  ^────^
- *The Church, composed of believing Jews and Gentiles, was established on the day of Pentecost.*

-  ^────^
- The Christian way of life involves study of the Scriptures so that we can grow in grace, live by faith, abide in Him, enjoy answered prayer, share spiritual gifts, and confess our sin privately to the Lord for restoration of fellowship.

-  ^────^
- *God’s strategy with the Church is the great commission to go to all nations and make disciples.*

-  ^────^
- Jesus is coming again soon for His Church at the rapture, and we should be waiting expectantly for Him.

-  ^────^
- *A time of trouble will come on the world, during which the nations will be punished and Israel will be brought to faith in Jesus as their Messiah.*

-  ^────^
- Jesus will return to set up His kingdom on earth where we will rule with Him as God originally intended.